FROM redis:7.2-alpine

RUN mkdir -p /redis/data /redis/conf

COPY redis.conf /redis/conf/redis.conf

RUN chown -R redis:redis /redis

EXPOSE 6379

WORKDIR /redis

CMD ["redis-server", "/redis/conf/redis.conf"] 