global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'task-queue-api'
    static_configs:
      - targets: ['api:8000']

  - job_name: 'task-queue-workers'
    static_configs:
      - targets: ['worker:8000']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379'] 