global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'task-queue-api'
    static_configs:
      - targets: ['api:8000']

  - job_name: 'task-queue-workers'
    static_configs:
      - targets: 
          - 'distributed-task-queue-worker-1:8000'
          - 'distributed-task-queue-worker-2:8000'
          - 'distributed-task-queue-worker-3:8000'
          - 'distributed-task-queue-worker-4:8000'
          - 'distributed-task-queue-worker-5:8000'
          - 'distributed-task-queue-worker-6:8000'
          - 'distributed-task-queue-worker-7:8000'
          - 'distributed-task-queue-worker-8:8000'
          - 'distributed-task-queue-worker-9:8000'
          - 'distributed-task-queue-worker-10:8000'


  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121'] 